# Generated by Django 4.1.2 on 2022-10-18 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "pm",
                    models.CharField(
                        choices=[
                            ("C", "Clean"),
                            ("R", "Replace worn parts"),
                            ("F", "Full tear-down"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "tools",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.tool"
                    ),
                ),
            ],
        ),
    ]
