# Generated by Django 4.1.2 on 2022-10-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_rename_pm_maintenance_maintenance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintenance",
            old_name="tools",
            new_name="tool",
        ),
    ]
