# Generated by Django 4.1.2 on 2022-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_rename_tools_maintenance_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="tool",
            name="storages",
            field=models.ManyToManyField(to="main_app.storage"),
        ),
    ]
